MVCLABSITI/Models/Instructor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCLABSITI.Models
{
    public class Instructor
    {
        [Key]
        public int InsId { get; set; }
        [RegularExpression("[a-zA-Z]{2,25}", ErrorMessage = "must be only letters btw [2,25]")]
        public string Name { get; set; }
        [Range(25,50, ErrorMessage = "Age must be btw [25:50]")]
        public int Age { get; set; }
        [Range(25000,70000, ErrorMessage = "Salary must be btw [25000:70000]")]
        public decimal Salary { get; set; }
        public string Image { get; set; }
        public DateTime HiringDate { get; set; }
        [RegularExpression("[a-zA-Z]{3,50}", ErrorMessage = "must be only letters btw [3,50]")]
        public string Address { get; set; }

        [ForeignKey(nameof(Department))]
        public int DeptId { get; set; }
        public Department Department { get; set; }
        public ICollection<CourseAssignment> CourseAssignmesnts { get; set; } = new HashSet<CourseAssignment>();

    }
}

MVCLABSITI/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using MVCLABSITI.Filters;
using MVCLABSITI.Models;
using MVCLABSITI.Repositories;

namespace MVCLABSITI.Controllers
{
    public class InstructorController : Controller
    {
        private readonly IGenericRepository<Instructor> _instructorRepo;
        private readonly IGenericRepository<Department> _departmentRepo;

        public InstructorController(
            IGenericRepository<Instructor> instructorRepo,
            IGenericRepository<Department> departmentRepo)
        {
            _instructorRepo = instructorRepo;
            _departmentRepo = departmentRepo;
        }

        public IActionResult getAll()
        {
            var instructors = _instructorRepo.GetAll();
            return View(instructors);
        }

        public IActionResult getById(int id)
        {
            var instructor = _instructorRepo.GetById(id);
            return View(instructor);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var departments = _departmentRepo.GetAll();
            ViewBag.departments = departments;
            return View();
        }

        [HttpPost]
        public IActionResult AddNew(Instructor instructor)
        {
            if (instructor.DeptId != 0)
            {
                if (ModelState.IsValid)
                {
                    _instructorRepo.Add(instructor);
                    _instructorRepo.Save();
                    return RedirectToAction("getAll");
                }
            }
            else
            {
                ModelState.AddModelError("DeptId", "Please select Department");
            }

            var departments = _departmentRepo.GetAll();
            ViewBag.departments = departments;
            return View("Add", instructor);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var instructor = _instructorRepo.GetById(id);
            var departments = _departmentRepo.GetAll();
            ViewBag.departments = departments;
            return View(instructor);
        }

        [HttpPost]
        [EditInstructorResultFilter]
        public IActionResult Edit(Instructor instructor)
        {
            if (instructor.DeptId != 0)
            {
                if (ModelState.IsValid)
                {
                    _instructorRepo.Update(instructor);
                    _instructorRepo.Save();
                    return RedirectToAction("getAll");
                }
            }
            else
            {
                ModelState.AddModelError("DeptId", "Please select Department");
            }

            return View(instructor);
        }

        public IActionResult Delete(int id)
        {
            var instructor = _instructorRepo.GetById(id);
            if (instructor != null)
            {
                _instructorRepo.Delete(instructor);
                _instructorRepo.Save();
            }
            return RedirectToAction("getAll"); 
        }
    }
}

MVCLABSITI/Views/Instructor/Add.cshtml
@model Instructor

<form action="/Instructor/AddNew" method="post">
    @* asp-action="AddNew" asp-controller="Instructor"   by tag helper *@
    <partial name="_AddEditPartialView" />
    <button type="submit" class="btn btn-primary">Add Instructor</button>
    <a href="/Instructor/GetAll" class="btn btn-secondary ms-2">Cancel</a>
</form>
@section Scripts
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}

    

MVCLABSITI/Views/Instructor/Delete.cshtml
@model Instructor
<form asp-action="Delete" asp-route-id="@Model.InsId" method="post">
    <input type="hidden" asp-for="InsId" />
    <button type="submit" class="btn btn-danger"> Delete </button>
</form>

MVCLABSITI/Views/Instructor/Edit.cshtml
@model Instructor

<form asp-action="Edit" asp-controller="Instructor" method="post">
    <input type="hidden" asp-for="InsId" />
    <partial name="_AddEditPartialView"/>
    <button type="submit" class="btn btn-primary">SaveEdits</button>
</form>
@section Scripts
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}

MVCLABSITI/Views/Instructor/_AddEditPartialView.cshtml
@model Instructor
@{
    SelectList departments = new SelectList(ViewBag.Departments, "DeptId", "Name");
}
<div class="mb-3">
    <label asp-for="Name"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>

</div>
<div class="mb-3">
    <label asp-for="Age"></label>
    <input asp-for="Age" class="form-control" />
    <span asp-validation-for="Age" class="text-danger"></span>

</div>
<div class="mb-3">
    <label asp-for="Salary"></label>
    <input asp-for="Salary" class="form-control" />
    <span asp-validation-for="Salary" class="text-danger"></span>

</div>
<div class="mb-3">
    <label asp-for="Image"></label>
    <input asp-for="Image" class="form-control" />
    <span asp-validation-for="Image" class="text-danger"></span>

</div>
<div class="mb-3">
    <label asp-for="HiringDate"></label>
    <input asp-for="HiringDate" class="form-control" />
    <span asp-validation-for="HiringDate" class="text-danger"></span>

</div>
<div class="mb-3">
    <label asp-for="Address"></label>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>

</div>
<div class="form-group">
    <label asp-for="DeptId"></label>
    <select class="form-control" asp-items="departments" asp-for="DeptId">
        <option value="0">-- Select Department --</option>
    </select>
    <span asp-validation-for="DeptId" class="text-danger"></span>
</div>

MVCLABSITI/Views/Instructor/getAll.cshtml
@model List<Instructor>

<a href="/Instructor/Add" class=" btn btn-outline-primary">New</a>


<table class="table">
    <thead>
        <tr>
            <th scope="col">InsId</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Salary</th>
            <th scope="col">Image</th>
            <th scope="col">HiringDate</th>
            <th scope="col">Address</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <th scope="row">@i.InsId</th>
                <td>@i.Name</td>
                <td>@i.Age</td>
                <td>@i.Salary</td>
                <td>@i.Image</td>
                <td>@i.HiringDate</td>
                <td>@i.Address</td>
                <td><a asp-action="Edit" asp-controller="Instructor" asp-route-id="@i.InsId" class="btn btn-outline-info">Edit</a></td>
                <td><a asp-action="Delete" asp-controller="Instructor" asp-route-id="@i.InsId" class="btn btn-outline-danger">Delete</a></td>
            </tr>
        }
    </tbody>
</table>
@section Header {
    <h2>Instructors</h2>
}
@section Footer {
    <p>ProximaEd</p>
}

MVCLABSITI/Views/Instructor/getById.cshtml
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Address</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>